# Generated by Django 4.1.7 on 2023-03-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proffesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=60)),
                ('second_name', models.CharField(max_length=60)),
                ('qualifiaction', models.CharField(max_length=60)),
                ('sexe', models.CharField(max_length=1)),
                ('birth_day', models.DateField()),
            ],
        ),
    ]
